### ISSUE TITLE
Does SSH server vulnerable in case of only publickey auth?

### ISSUE THREAD

**Issue by DASAR** [c0r3dump3d/osueta#3]
I'm interesting in case of only publickey auth allowed (but server version is 6.0p1, valnurable):
Bad authentication type (allowed_types=['publickey'])

**Comment by c0r3dump3d** [comment]
Hi, no, in the case of only publickey_auth the server it's no vulnerable to the time attack. The server doesn't need to evaluate the hash of the password, only check the public key.
